/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Parte2;

import javax.swing.JOptionPane;

/**
 *
 * @author JEFERSON
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        txtFigura = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escribe el nombre de la figura a la que le quieres calcular el area y el perimetro sin espacios:");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");

        jLabel2.setText("(Circulo, rectangulo, cuadrado, triangulo rectangulo, rombo, trapecio)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnCalcular)
                        .addGap(85, 85, 85)
                        .addComponent(btnBorrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(txtFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(txtFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnBorrar))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String figura = txtFigura.getText();
        figura = figura.toLowerCase();
        switch (figura) {
            case "circulo":
                int radio = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el radio del circulo: "));
                Circulo figura1 = new Circulo(radio);
                JOptionPane.showMessageDialog(null, "El área del círculo es = " + figura1.calcularArea());
                JOptionPane.showMessageDialog(null, "El perímetro del círculo es = " + figura1.calcularPerimetro());
                break;

            case "rectangulo":
                int baseR = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la base del rectangulo: "));
                int alturaR = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la altura del rectangulo: "));
                Rectangulo figura2 = new Rectangulo(baseR, alturaR);
                JOptionPane.showMessageDialog(null, "El área del rectangulo es = " + figura2.calcularArea());
                JOptionPane.showMessageDialog(null, "El perímetro del rectangulo es = " + figura2.calcularPerímetro());
                break;

            case "cuadrado":
                int ladoC = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el lado del rectangulo: "));
                Cuadrado figura3 = new Cuadrado(ladoC);
                JOptionPane.showMessageDialog(null, "El área del cuadrado es = " + figura3.calcularArea());
                JOptionPane.showMessageDialog(null, "El perímetro del cuadrado es = " + figura3.calcularPerímetro());
                break;
            case "triangulorectangulo":
                int baseTR = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la base del Triangulo rectangulo: "));
                int alturaTR = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la altura del Triangulo rectangulo: "));
                TrianguloRectangulo figura4 = new TrianguloRectangulo(baseTR, alturaTR);
                JOptionPane.showMessageDialog(null, "El área del triangulo rectangulo es = " + figura4.calcularArea());
                JOptionPane.showMessageDialog(null, "El perímetro del triangulo rectangulo es = " + figura4.calcularPerímetro());
                break;

            case "rombo":
                int ladoR = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el lado del rombo: "));
                int dmayorR = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la diagonal mayor del rombo: "));
                int dmenorR = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la diagonal menor del rombo: "));

                Rombo figura5 = new Rombo(ladoR, dmayorR, dmenorR);
                JOptionPane.showMessageDialog(null, "El área del rombo es = " + figura5.calcularArea());
                JOptionPane.showMessageDialog(null, "El perímetro del rombo es = " + figura5.calcularPerimetro());
                break;
            case "trapecio":
                int base1T = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la base 1 del trapecio: "));
                int base2T = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la base 2 del trapecio: "));
                int alturaT = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la altura del trapecio: "));
                int lado1T = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el lado 1 del trapecio: "));
                int lado2T = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el lado 2 del trapecio: "));
                Trapecio figura6 = new Trapecio(base1T, base2T, alturaT, lado1T, lado2T);
                JOptionPane.showMessageDialog(null, "El área del trapecio rectangulo es = " + figura6.calcularArea());
                JOptionPane.showMessageDialog(null, "El perímetro del trapecio rectangulo es = " + figura6.calcularPerimetro());
                break;

        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtFigura;
    // End of variables declaration//GEN-END:variables
}
